apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: simple-composition-v1alpha1
spec:
  mode: Pipeline
  compositeTypeRef:
    apiVersion: example.guidewire.net/v1alpha1
    kind: xSimple
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      - name: themap
        base:
          apiVersion: kubernetes.crossplane.io/v1alpha2
          kind: Object
          spec:
            forProvider:
              manifest:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  namespace: default
                data:
                  constant: first version
                  foo: replace me
        patches:
          - type: FromCompositeFieldPath
            fromFieldPath: spec.foo
            toFieldPath: spec.forProvider.manifest.data.foo